### ISSUE TITLE
Build errors when building git on MacOS 11 (x86-64) and for M1 macs

### ISSUE THREAD

**Issue by nikhil2611** [git/git.github.io#509]
When building Git  on MacOS 11.0 / m1 macs for my app, I'm running into the following error

_NOTE: This doesn't doesn't seem to be a problem with building 10.15 or 10.14._

```
[Builder: git-custom-bindir] I \| 2021-06-01T11:37:45-07:00 \| Build git-custom-bindir: 7.0445s
--
&nbsp; | The following shell command exited with status 2:
&nbsp; | &nbsp;
&nbsp; | $ CFLAGS=-I/opt/chef-workstation/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector CPPFLAGS=-I/opt/chef-workstation/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector CXXFLAGS=-I/opt/chef-workstation/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector LDFLAGS=-Wl,-rpath,/opt/chef-workstation/embedded/lib -L/opt/chef-workstation/embedded/lib LD_RUN_PATH=/opt/chef-workstation/embedded/lib MAKE=gmake OMNIBUS_INSTALL_DIR=/opt/chef-workstation PATH=/opt/chef-workstation/bin:/opt/chef-workstation/embedded/bin:/Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bin:/opt/angry-omnibus-toolchain/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin PKG_CONFIG_PATH=/opt/chef-workstation/embedded/lib/pkgconfig gmake prefix=/opt/chef-workstation/embedded bindir=/opt/chef-workstation/gitbin -j 10
&nbsp; | &nbsp;
&nbsp; | Output:
&nbsp; | &nbsp;
&nbsp; | CC fuzz-commit-graph.o
&nbsp; | CC fuzz-pack-headers.o
&nbsp; | CC fuzz-pack-idx.o
&nbsp; | CC daemon.o
&nbsp; | CC common-main.o
&nbsp; | CC add-interactive.o
&nbsp; | CC abspath.o
&nbsp; | CC alias.o
&nbsp; | CC add-patch.o
&nbsp; | CC alloc.o
&nbsp; | CC advice.o
&nbsp; | CC apply.o
&nbsp; | CC archive-tar.o
&nbsp; | CC archive-zip.o
&nbsp; | CC archive.o
&nbsp; | CC base85.o
&nbsp; | CC bisect.o
&nbsp; | CC blame.o
&nbsp; | CC blob.o
&nbsp; | CC bloom.o
&nbsp; | CC branch.o
&nbsp; | CC bulk-checkin.o
&nbsp; | CC bundle.o
&nbsp; | CC cache-tree.o
&nbsp; | CC chdir-notify.o
&nbsp; | CC checkout.o
&nbsp; | CC chunk-format.o
&nbsp; | CC color.o
&nbsp; | CC column.o
&nbsp; | CC combine-diff.o
&nbsp; | CC commit-graph.o
&nbsp; | CC commit-reach.o
&nbsp; | CC commit.o
&nbsp; | CC compat/obstack.o
&nbsp; | CC compat/terminal.o
&nbsp; | CC config.o
&nbsp; | CC connect.o
&nbsp; | CC connected.o
&nbsp; | CC convert.o
&nbsp; | CC copy.o
&nbsp; | CC credential.o
&nbsp; | CC csum-file.o
&nbsp; | CC ctype.o
&nbsp; | CC date.o
&nbsp; | CC decorate.o
&nbsp; | CC delta-islands.o
&nbsp; | CC diff-delta.o
&nbsp; | CC diff-merges.o
&nbsp; | CC diff-lib.o
&nbsp; | CC diff-no-index.o
&nbsp; | CC diff.o
&nbsp; | CC diffcore-break.o
&nbsp; | CC diffcore-delta.o
&nbsp; | CC diffcore-order.o
&nbsp; | CC diffcore-pickaxe.o
&nbsp; | CC diffcore-rename.o
&nbsp; | CC diffcore-rotate.o
&nbsp; | CC dir-iterator.o
&nbsp; | CC dir.o
&nbsp; | CC editor.o
&nbsp; | CC entry.o
&nbsp; | CC environment.o
&nbsp; | CC ewah/bitmap.o
&nbsp; | CC ewah/ewah_bitmap.o
&nbsp; | CC ewah/ewah_io.o
&nbsp; | CC ewah/ewah_rlw.o
&nbsp; | CC exec-cmd.o
&nbsp; | CC fetch-negotiator.o
&nbsp; | CC fetch-pack.o
&nbsp; | CC fmt-merge-msg.o
&nbsp; | CC fsck.o
&nbsp; | CC fsmonitor.o
&nbsp; | CC gettext.o
&nbsp; | CC gpg-interface.o
&nbsp; | CC graph.o
&nbsp; | CC grep.o
&nbsp; | CC hash-lookup.o
&nbsp; | CC hashmap.o
&nbsp; | GEN command-list.h
&nbsp; | CC hex.o
&nbsp; | CC ident.o
&nbsp; | CC json-writer.o
&nbsp; | CC kwset.o
&nbsp; | CC levenshtein.o
&nbsp; | CC line-log.o
&nbsp; | CC line-range.o
&nbsp; | CC linear-assignment.o
&nbsp; | CC list-objects-filter-options.o
&nbsp; | CC list-objects-filter.o
&nbsp; | CC list-objects.o
&nbsp; | CC ll-merge.o
&nbsp; | CC lockfile.o
&nbsp; | CC log-tree.o
&nbsp; | CC ls-refs.o
&nbsp; | CC mailinfo.o
&nbsp; | CC mailmap.o
&nbsp; | CC match-trees.o
&nbsp; | CC mem-pool.o
&nbsp; | CC merge-blobs.o
&nbsp; | CC merge-ort.o
&nbsp; | CC merge-ort-wrappers.o
&nbsp; | CC merge-recursive.o
&nbsp; | CC merge.o
&nbsp; | CC mergesort.o
&nbsp; | CC midx.o
&nbsp; | CC name-hash.o
&nbsp; | CC negotiator/default.o
&nbsp; | CC negotiator/noop.o
&nbsp; | CC negotiator/skipping.o
&nbsp; | CC notes-cache.o
&nbsp; | CC notes-merge.o
&nbsp; | CC notes-utils.o
&nbsp; | CC notes.o
&nbsp; | CC object-file.o
&nbsp; | CC object-name.o
&nbsp; | CC object.o
&nbsp; | CC oid-array.o
&nbsp; | CC oidmap.o
&nbsp; | CC oidset.o
&nbsp; | CC pack-bitmap-write.o
&nbsp; | CC pack-bitmap.o
&nbsp; | CC pack-check.o
&nbsp; | CC pack-objects.o
&nbsp; | CC pack-revindex.o
&nbsp; | CC pack-write.o
&nbsp; | CC packfile.o
&nbsp; | CC pager.o
&nbsp; | CC parse-options-cb.o
&nbsp; | CC parse-options.o
&nbsp; | CC patch-delta.o
&nbsp; | CC patch-ids.o
&nbsp; | CC path.o
&nbsp; | CC pathspec.o
&nbsp; | CC pkt-line.o
&nbsp; | CC preload-index.o
&nbsp; | CC pretty.o
&nbsp; | CC prio-queue.o
&nbsp; | CC progress.o
&nbsp; | CC promisor-remote.o
&nbsp; | CC prompt.o
&nbsp; | CC protocol.o
&nbsp; | CC prune-packed.o
&nbsp; | CC quote.o
&nbsp; | CC range-diff.o
&nbsp; | CC reachable.o
&nbsp; | CC read-cache.o
&nbsp; | CC rebase-interactive.o
&nbsp; | CC rebase.o
&nbsp; | CC ref-filter.o
&nbsp; | CC reflog-walk.o
&nbsp; | CC refs.o
&nbsp; | CC refs/debug.o
&nbsp; | CC refs/files-backend.o
&nbsp; | CC refs/iterator.o
&nbsp; | CC refs/packed-backend.o
&nbsp; | CC refs/ref-cache.o
&nbsp; | CC refspec.o
&nbsp; | CC remote.o
&nbsp; | CC replace-object.o
&nbsp; | CC repo-settings.o
&nbsp; | CC repository.o
&nbsp; | CC rerere.o
&nbsp; | CC reset.o
&nbsp; | CC resolve-undo.o
&nbsp; | CC revision.o
&nbsp; | CC run-command.o
&nbsp; | CC send-pack.o
&nbsp; | CC sequencer.o
&nbsp; | CC serve.o
&nbsp; | CC server-info.o
&nbsp; | CC setup.o
&nbsp; | CC shallow.o
&nbsp; | CC sideband.o
&nbsp; | CC sigchain.o
&nbsp; | CC split-index.o
&nbsp; | CC stable-qsort.o
&nbsp; | CC strbuf.o
&nbsp; | CC streaming.o
&nbsp; | CC string-list.o
&nbsp; | CC strmap.o
&nbsp; | CC strvec.o
&nbsp; | CC sub-process.o
&nbsp; | CC submodule-config.o
&nbsp; | CC submodule.o
&nbsp; | CC symlinks.o
&nbsp; | CC tag.o
&nbsp; | CC tempfile.o
&nbsp; | CC thread-utils.o
&nbsp; | CC tmp-objdir.o
&nbsp; | CC trace.o
&nbsp; | CC trace2.o
&nbsp; | CC trace2/tr2_cfg.o
&nbsp; | CC trace2/tr2_cmd_name.o
&nbsp; | CC trace2/tr2_dst.o
&nbsp; | CC trace2/tr2_sid.o
&nbsp; | CC trace2/tr2_sysenv.o
&nbsp; | CC trace2/tr2_tbuf.o
&nbsp; | CC trace2/tr2_tgt_event.o
&nbsp; | CC trace2/tr2_tgt_normal.o
&nbsp; | CC trace2/tr2_tgt_perf.o
&nbsp; | CC trace2/tr2_tls.o
&nbsp; | CC trailer.o
&nbsp; | CC transport-helper.o
&nbsp; | CC transport.o
&nbsp; | CC tree-diff.o
&nbsp; | CC tree-walk.o
&nbsp; | CC tree.o
&nbsp; | CC unpack-trees.o
&nbsp; | CC upload-pack.o
&nbsp; | CC url.o
&nbsp; | CC usage.o
&nbsp; | CC urlmatch.o
&nbsp; | CC userdiff.o
&nbsp; | CC utf8.o
&nbsp; | CC varint.o
&nbsp; | CC versioncmp.o
&nbsp; | CC walker.o
&nbsp; | CC wildmatch.o
&nbsp; | CC worktree.o
&nbsp; | CC wrapper.o
&nbsp; | CC write-or-die.o
&nbsp; | CC ws.o
&nbsp; | CC wt-status.o
&nbsp; | CC xdiff-interface.o
&nbsp; | CC zlib.o
&nbsp; | CC unix-socket.o
&nbsp; | CC compat/sha1-chunked.o
&nbsp; | CC sha256/block/sha256.o
&nbsp; | CC compat/precompose_utf8.o
&nbsp; | CC compat/fopen.o
&nbsp; | CC compat/open.o
&nbsp; | CC compat/memmem.o
&nbsp; | CC compat/qsort_s.o
&nbsp; | CC compat/regex/regex.o
&nbsp; | CC xdiff/xdiffi.o
&nbsp; | CC xdiff/xemit.o
&nbsp; | CC xdiff/xhistogram.o
&nbsp; | CC xdiff/xpatience.o
&nbsp; | CC xdiff/xmerge.o
&nbsp; | CC xdiff/xprepare.o
&nbsp; | CC xdiff/xutils.o
&nbsp; | CC http-backend.o
&nbsp; | CC imap-send.o
&nbsp; | CC http.o
&nbsp; | CC sh-i18n--envsubst.o
&nbsp; | CC shell.o
&nbsp; | CC http-walker.o
&nbsp; | CC http-fetch.o
&nbsp; | CC http-push.o
&nbsp; | CC remote-curl.o
&nbsp; | GEN git-instaweb
&nbsp; | CC git.o
&nbsp; | CC builtin/add.o
&nbsp; | CC builtin/am.o
&nbsp; | CC builtin/annotate.o
&nbsp; | CC builtin/apply.o
&nbsp; | CC builtin/archive.o
&nbsp; | CC builtin/bisect--helper.o
&nbsp; | CC builtin/blame.o
&nbsp; | CC builtin/branch.o
&nbsp; | CC builtin/bugreport.o
&nbsp; | &nbsp;
&nbsp; | Error:
&nbsp; | &nbsp;
&nbsp; | GIT_VERSION = 2.31.1
&nbsp; | * new build flags
&nbsp; | * new link flags
&nbsp; | * new prefix flags
&nbsp; | * new script parameters
&nbsp; | builtin/archive.c:48:24: error: implicit declaration of function 'archive_format_from_filename' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
&nbsp; | const char *format = archive_format_from_filename(name_hint);
&nbsp; | ^
&nbsp; | builtin/archive.c:48:24: note: did you mean 'archive_read_open_filename'?
&nbsp; | /opt/chef-workstation/embedded/include/archive.h:527:15: note: 'archive_read_open_filename' declared here
&nbsp; | __LA_DECL int archive_read_open_filename(struct archive *,
&nbsp; | ^
&nbsp; | builtin/archive.c:48:15: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
&nbsp; | const char *format = archive_format_from_filename(name_hint);
&nbsp; | ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
&nbsp; | builtin/archive.c:101:2: error: implicit declaration of function 'init_archivers' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
&nbsp; | init_archivers();
&nbsp; | ^
&nbsp; | builtin/archive.c:111:9: error: implicit declaration of function 'write_archive' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
&nbsp; | return write_archive(argc, argv, prefix, the_repository, output, 0);
&nbsp; | ^
&nbsp; | builtin/archive.c:111:9: note: did you mean 'write_or_die'?
&nbsp; | ./cache.h:1737:6: note: 'write_or_die' declared here
&nbsp; | void write_or_die(int fd, const void *buf, size_t count);
&nbsp; | ^
&nbsp; | 1 warning and 3 errors generated.
&nbsp; | gmake: *** [Makefile:2431: builtin/archive.o] Error 1
&nbsp; | gmake: *** Waiting for unfinished jobs....
&nbsp; | &nbsp;
&nbsp; | &nbsp;
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/util.rb:139:in `rescue in shellout!'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/util.rb:134:in `shellout!'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:871:in `shellout!'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:85:in `block in command'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:1061:in `instance_eval'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:1061:in `run'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:889:in `block (3 levels) in execute'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:911:in `with_retries'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:888:in `block (2 levels) in execute'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/instrumentation.rb:23:in `measure'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:887:in `block in execute'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:962:in `with_clean_env'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:886:in `execute'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:778:in `block (2 levels) in build'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:777:in `each'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:777:in `block in build'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/instrumentation.rb:23:in `measure'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/builder.rb:776:in `build'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/software.rb:1224:in `execute_build'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/software.rb:1102:in `build_me'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/project.rb:1078:in `block (2 levels) in build'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/project.rb:1077:in `each'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/project.rb:1077:in `block in build'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/licensing.rb:62:in `block in create_incrementally'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/licensing.rb:57:in `tap'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/licensing.rb:57:in `create_incrementally'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/project.rb:1076:in `build'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/cli.rb:89:in `build'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/cli/base.rb:33:in `dispatch'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/cli.rb:42:in `execute!'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-87db446ee0b9/bin/omnibus:16:in `&lt;top (required)&gt;'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bin/omnibus:23:in `load'
&nbsp; | /Users/administrator/.buildkite-agent/builds/MM009-local-1/chef/chef-chef-workstation-master-omnibus-adhoc/omnibus/vendor/bundle/ruby/2.7.0/bin/omnibus:23:in `&lt;top (required)&gt;'
&nbsp; | /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
&nbsp; | /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
&nbsp; | /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
&nbsp; | /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:494:in `exec'
&nbsp; | /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
&nbsp; | /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
&nbsp; | /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
&nbsp; | /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
&nbsp; | /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
&nbsp; | /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:24:in `start'
&nbsp; | /opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.2.12/exe/bundle:49:in `block in &lt;top (required)&gt;'
&nbsp; | /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
&nbsp; | /opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.2.12/exe/bundle:37:in `&lt;top (required)&gt;'
&nbsp; | /opt/angry-omnibus-toolchain/bin/bundle:23:in `load'
&nbsp; | /opt/angry-omnibus-toolchain/bin/bundle:23:in `&lt;main&gt;'
&nbsp; | 🚨 Error: The command exited with status 1
```

Some other relevant build environment information:

```
========================================
= Tool Versions
========================================
Bash.........GNU bash, version 5.0.0(1)-release (x86_64-apple-darwin17.7.0)
Bundler......Bundler version 2.1.4
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
GCC..........Apple clang version 12.0.0 (clang-1200.0.32.28)
platform........mac_os_x-11-arm64
Git..........git version 2.31.1
Make.........GNU Make 4.2.1
Ruby.........ruby 2.7.3
RubyGems.....3.1.4
========================================
```

**Comment by chriscool** [comment]
Sorry but this is not the place for such bug reports. Please send this to the Git Mailing list (maybe after using `git bugreport`) as described on the Bug Reporting section of: https://git-scm.com/community
